// <auto-generated />
using Lansoy.RG.DAL.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lansoy.RG.DAL.Migrations
{
    [DbContext(typeof(LansoyDbContext))]
    [Migration("20240419122636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Espion", b =>
                {
                    b.Property<int>("EspionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EspionId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomDeCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EspionId");

                    b.ToTable("Espions");
                });

            modelBuilder.Entity("EspionMission", b =>
                {
                    b.Property<int>("EspionsEspionId")
                        .HasColumnType("int");

                    b.Property<int>("MissionsMissionId")
                        .HasColumnType("int");

                    b.HasKey("EspionsEspionId", "MissionsMissionId");

                    b.HasIndex("MissionsMissionId");

                    b.ToTable("EspionMission");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MissionId"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MissionId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("EspionMission", b =>
                {
                    b.HasOne("Espion", null)
                        .WithMany()
                        .HasForeignKey("EspionsEspionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
